server:
port: 9090
servlet: context-path: /api

spring:
application:
name: NewsPortal Backend

datasource:
url: jdbc:postgresql://localhost/portal_news
username: postgres
password: 2505
driver-class-name: org.postgresql.Driver

# H2 para desenvolvimento (comentar PostgreSQL acima e descomentar abaixo)
# datasource:
#   url: jdbc:h2:mem:testdb
#   driver-class-name: org.h2.Driver
#   username: sa
#   password: password
# h2:
#   console:
#     enabled: true

jpa:
ddl-auto: update
show-sql: true
properties:
hibernate:
dialect: org.hibernate.dialect.PostgreSQLDialect
format_sql: true

multipart:
max-file-size: 10MB
max-request-size: 10MB

file:
upload-dir: uploads/images

logging:
level:
com.newsportal: DEBUG
org.springframework.security: DEBUG